"""The rule index — every rule this repo enforces, and the test that enforces it.

    python -m core.rules            print the table
    python -m core.rules --write    rewrite the table inside AGENTS.md

**Why this exists.** Most rules in `AGENTS.md` are enforced by a test, and a few are not because they
cannot be. Nothing said which was which. So a rule written as prose — *"the single generation path …
never build a second one"* — read as an honour-system plea, when `core/test_single_path.py` has
enforced it all along and opens with *"as a test rather than a promise"*. On 2026-07-30 an agent read
that sentence, inferred a gap that did not exist, and reported it as a finding. The entry point was
hiding its own enforcement.

**How a test joins the index:** declare a module-level `RULE` string in it. That is the whole contract
— no registry to update here, no naming convention to obey, and a test file with no `RULE` is simply
an ordinary test rather than a guard. Keep it to one line, in the imperative, describing *the rule*
rather than the test.

**This is a generator, not a test.** Nothing asserts the table in `AGENTS.md` is current, deliberately:
prose has no honest schema and this repo does not test its documentation. The cost is that the table
can go stale; the mitigation is that regenerating it is one command and it is idempotent, so it is a
cheap step in `/publish` or in any session that adds a guard.
"""
from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AGENTS = ROOT / "AGENTS.md"

BEGIN = "<!-- RULES:BEGIN — generated by `python -m core.rules --write`; edit the tests, not this -->"
END = "<!-- RULES:END -->"

#: Directories that are not part of the repo's own suite.
_SKIP = (".claude", ".venv", ".git", ".scratch", "__pycache__")


def _rule_of(path: Path) -> str | None:
    """The module-level `RULE` string in a test file, or None if it declares none.

    Parsed rather than imported: importing every test module to read one constant would execute
    collection-time code, and a generator that can fail because a test file has a heavy import is a
    generator nobody runs.
    """
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (SyntaxError, UnicodeDecodeError):
        return None
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        names = [t.id for t in node.targets if isinstance(t, ast.Name)]
        if "RULE" in names and isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
            return " ".join(node.value.value.split())
    return None


def collect(root: Path = ROOT) -> list[tuple[str, str]]:
    """Every `(repo-relative test path, rule)` pair, sorted by path."""
    found = []
    for path in sorted(root.rglob("test_*.py")):
        rel = path.relative_to(root)
        if any(part in _SKIP for part in rel.parts):
            continue
        rule = _rule_of(path)
        if rule:
            found.append((rel.as_posix(), rule))
    return found


def table(rules: list[tuple[str, str]]) -> str:
    """The markdown table, between its generated-content markers."""
    lines = [
        BEGIN,
        "",
        f"**{len(rules)} rules in this repo are enforced by a test.** If a rule is in this table, do "
        "not report it as unenforced — read the test. If a rule is *not* here, it is prose and holds "
        "only as far as the reader's attention does.",
        "",
        "| the rule | enforced by |",
        "|---|---|",
    ]
    lines += [f"| {rule} | `{path}` |" for path, rule in rules]
    lines += ["", f"Regenerate with `python -m core.rules --write`. A test joins this table by "
                  f"declaring a module-level `RULE` string; see `core/rules.py`.", "", END]
    return "\n".join(lines)


def write(root: Path = ROOT) -> bool:
    """Replace the marked block in AGENTS.md. Returns True when the file changed."""
    agents = root / "AGENTS.md"
    text = agents.read_text(encoding="utf-8")
    block = table(collect(root))
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pattern.search(text):
        raise SystemExit(
            f"{agents} has no RULES block. Add these two lines where the table belongs:\n"
            f"  {BEGIN}\n  {END}"
        )
    updated = pattern.sub(lambda _: block, text)
    if updated == text:
        return False
    agents.write_text(updated, encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if "--write" in argv:
        print("AGENTS.md updated" if write() else "AGENTS.md already current")
    else:
        print(table(collect()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
